package game

import "sync"

var economyResourcesOnce sync.Once

// registerEconomyResources adiciona as matérias-primas profissionais, materiais
// de monstros, produtos processados, catalisadores e sucatas da Economia V2.
func registerEconomyResources() {
	definitions := []ResourceDefinition{
		{Key: "resin", Name: "Resina", Icon: "🟤", Rarity: "Comum", Description: "Seiva coletada por lenhadores.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "lumberjack", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "seeds", Name: "Sementes", Icon: "🌱", Rarity: "Comum", Description: "Sementes para cultivo e receitas.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "farmer", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "wheat", Name: "Trigo", Icon: "🌾", Rarity: "Comum", Description: "Cereal colhido em expedições agrícolas.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "farmer", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "herbs", Name: "Ervas", Icon: "🌿", Rarity: "Incomum", Description: "Ervas usadas em alimentos e alquimia.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "herbalist", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "arcane_blossom", Name: "Flor Arcana", Icon: "🪻", Rarity: "Raro", Description: "Flor rara colhida por herbalistas experientes.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "herbalist", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "raw_fish", Name: "Peixe Fresco", Icon: "🐟", Rarity: "Comum", Description: "Peixe obtido por pescadores.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "fisher", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "fish_scale", Name: "Escama de Peixe", Icon: "🐠", Rarity: "Incomum", Description: "Escamas resistentes para acessórios.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "fisher", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "raw_meat", Name: "Carne Fresca", Icon: "🥩", Rarity: "Comum", Description: "Carne obtida por rastreadores.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "tracker", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "raw_hide", Name: "Couro Cru", Icon: "🦬", Rarity: "Comum", Description: "Pele animal que precisa ser curtida.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "tracker", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "animal_bone", Name: "Osso de Caça", Icon: "🦴", Rarity: "Comum", Description: "Ossos limpos encontrados por rastreadores em clareiras de caça. Podem ser usados em reforços e receitas de artesanato.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "tracker", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "coal", Name: "Carvão Mineral", Icon: "⬛", Rarity: "Comum", Description: "Combustível para fundição.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "miner", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "copper_ore", Name: "Minério de Cobre", Icon: "🟠", Rarity: "Comum", Description: "Minério maleável de baixo tier.", MaxStack: 999999, Category: ResourceCategoryProfessionRaw, CountsTowardStorage: true, Discardable: true, SourceKind: "gathering", ProfessionKey: "miner", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},

		{Key: "treated_plank", Name: "Tábua Tratada", Icon: "🪚", Rarity: "Incomum", Description: "Madeira processada para equipamentos.", MaxStack: 999999, Category: ResourceCategoryProcessed, CountsTowardStorage: true, Discardable: true, SourceKind: "crafting", ProfessionKey: "lumberjack", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "iron_ingot", Name: "Lingote de Ferro", Icon: "🔩", Rarity: "Incomum", Description: "Ferro fundido e pronto para a forja.", MaxStack: 999999, Category: ResourceCategoryProcessed, CountsTowardStorage: true, Discardable: true, SourceKind: "crafting", ProfessionKey: "miner", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "woven_cloth", Name: "Tecido Trançado", Icon: "🧵", Rarity: "Incomum", Description: "Fibra transformada em tecido resistente.", MaxStack: 999999, Category: ResourceCategoryProcessed, CountsTowardStorage: true, Discardable: true, SourceKind: "crafting", ProfessionKey: "farmer", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "tanned_leather", Name: "Couro Curtido", Icon: "🟫", Rarity: "Incomum", Description: "Couro pronto para armaduras e bolsas.", MaxStack: 999999, Category: ResourceCategoryProcessed, CountsTowardStorage: true, Discardable: true, SourceKind: "crafting", ProfessionKey: "tracker", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "flour", Name: "Farinha", Icon: "⚪", Rarity: "Comum", Description: "Trigo moído para alimentos.", MaxStack: 999999, Category: ResourceCategoryProcessed, CountsTowardStorage: true, Discardable: true, SourceKind: "crafting", ProfessionKey: "farmer", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},

		// Refeições produzidas na Cozinha de Campanha. São recursos empilháveis até
		// serem consumidos; o efeito ativo é persistido separadamente no PostgreSQL.
		{Key: "grilled_fish", Name: "Peixe Assado", Icon: "🍽️", Rarity: "Comum", Description: "Peixe tostado no fogo. +5% XP de combate por 20 min.", MaxStack: 99999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "cooking", ProfessionKey: "cook", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 3},
		{Key: "hunter_skewer", Name: "Espeto do Caçador", Icon: "🍢", Rarity: "Comum", Description: "Carne temperada com ervas. +5% poder de ataque por 20 min.", MaxStack: 99999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "cooking", ProfessionKey: "cook", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 3},
		{Key: "explorer_stew", Name: "Ensopado do Explorador", Icon: "🥘", Rarity: "Incomum", Description: "Refeição de longa duração. +8% XP de combate por 5 h.", MaxStack: 99999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "cooking", ProfessionKey: "cook", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 3},
		{Key: "tracker_pie", Name: "Torta do Rastreador", Icon: "🥧", Rarity: "Incomum", Description: "Torta reforçada para expedições. +7% poder de ataque por 5 h.", MaxStack: 99999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "cooking", ProfessionKey: "cook", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 3},
		{Key: "arcane_banquet", Name: "Banquete Arcano", Icon: "🍱", Rarity: "Épico", Description: "Banquete temperado com Flor Arcana. +12% XP de combate por 24 h.", MaxStack: 9999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "cooking", ProfessionKey: "cook", Tier: 3, StorageWeight: 1, Tradeable: true, ContentVersion: 3},
		{Key: "warrior_banquet", Name: "Banquete do Guerreiro", Icon: "🍖", Rarity: "Épico", Description: "Banquete pesado de campanha. +10% poder de ataque por 24 h.", MaxStack: 9999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "cooking", ProfessionKey: "cook", Tier: 3, StorageWeight: 1, Tradeable: true, ContentVersion: 3},
		{Key: "minor_strength_elixir", Name: "Tônico de Força", Icon: "🧪", Rarity: "Comum", Description: "Poção alquímica simples. +5% poder de ataque por 30 min. Ocupa o espaço de poção, sem substituir uma refeição.", MaxStack: 99999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "alchemy", ProfessionKey: "alchemist", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 1},
		{Key: "focus_tonic", Name: "Tônico de Foco", Icon: "🔵", Rarity: "Comum", Description: "Poção alquímica simples. +5% XP de combate por 30 min. Ocupa o espaço de poção, sem substituir uma refeição.", MaxStack: 99999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "alchemy", ProfessionKey: "alchemist", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 1},
		{Key: "arcane_draught", Name: "Elixir Arcano", Icon: "🔮", Rarity: "Incomum", Description: "Elixir concentrado. +8% poder de ataque por 5 h. Ocupa o espaço de poção.", MaxStack: 99999, Category: ResourceCategoryConsumable, CountsTowardStorage: true, Discardable: true, SourceKind: "alchemy", ProfessionKey: "alchemist", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 1},

		{Key: "quality_dust", Name: "Pó de Qualidade", Icon: "✨", Rarity: "Raro", Description: "Catalisador consumido em 1 unidade por craft. Reduz a chance de itens Comuns e aumenta as chances de Incomuns, Raros e Épicos; não garante uma raridade.", MaxStack: 99999, Category: ResourceCategoryCatalyst, CountsTowardStorage: true, Discardable: true, SourceKind: "boss_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "prismatic_core", Name: "Núcleo Prismático", Icon: "💠", Rarity: "Épico", Description: "Catalisador avançado consumido em 1 unidade por craft. Aumenta fortemente as chances de Raros, Épicos e Lendários; não garante uma raridade.", MaxStack: 99999, Category: ResourceCategoryCatalyst, CountsTowardStorage: true, Discardable: true, SourceKind: "boss_drop", Tier: 4, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "metal_scrap", Name: "Sucata Metálica", Icon: "⚙️", Rarity: "Comum", Description: "Metal recuperado no desmonte; não substitui mineração.", MaxStack: 999999, Category: ResourceCategoryScrap, CountsTowardStorage: true, Discardable: true, SourceKind: "salvage", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "cloth_scrap", Name: "Retalho", Icon: "🧶", Rarity: "Comum", Description: "Tecido recuperado no desmonte.", MaxStack: 999999, Category: ResourceCategoryScrap, CountsTowardStorage: true, Discardable: true, SourceKind: "salvage", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "arcane_scrap", Name: "Pó Arcano Residual", Icon: "🟣", Rarity: "Incomum", Description: "Resíduo mágico recuperado ao desmontar equipamentos. É matéria-prima para a Essência Arcana.", MaxStack: 999999, Category: ResourceCategoryScrap, CountsTowardStorage: true, Discardable: true, SourceKind: "salvage", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},

		{Key: "part_goblin_ear", Name: "Orelha de Goblin", Icon: "👂", Rarity: "Comum", Description: "Prova de uma caçada na floresta.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_wolf_fang", Name: "Presa de Lobo", Icon: "🦷", Rarity: "Comum", Description: "Presa afiada de lobo selvagem.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_spider_silk", Name: "Seda de Aranha Espinhosa", Icon: "🕸️", Rarity: "Incomum", Description: "Seda elástica e resistente.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_bear_claw", Name: "Lasca de Garra Ranzinza", Icon: "🐾", Rarity: "Raro", Description: "Fragmento de garra do urso chefe.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_ogre_wart", Name: "Verruga de Ogre Verde", Icon: "🟢", Rarity: "Comum", Description: "Ingrediente desagradavelmente útil.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_donkey_tooth", Name: "Dente do Burro Falante", Icon: "🫏", Rarity: "Incomum", Description: "Ainda parece estar reclamando.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_fiona_tiara_shard", Name: "Fragmento da Tiara da Fiona", Icon: "👑", Rarity: "Raro", Description: "Componente régio do pântano.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_pirate_hook", Name: "Gancho de Pirata Quebrado", Icon: "🪝", Rarity: "Comum", Description: "Metal salgado dos mares de Chapolin.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_tripa_belt", Name: "Fivela do Tripa", Icon: "🔗", Rarity: "Comum", Description: "Fivela roubada e muito usada.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_bandit_mask", Name: "Retalho de Máscara do Bandido", Icon: "🥷", Rarity: "Incomum", Description: "Tecido de identidade questionável.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_black_soul_emblem", Name: "Lasca do Brasão da Alma Negra", Icon: "🏴‍☠️", Rarity: "Raro", Description: "Emblema enegrecido pelo mar.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 1, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_orc_tusk", Name: "Presa de Orc", Icon: "🦷", Rarity: "Comum", Description: "Presa robusta das ruínas.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_orc_rune", Name: "Runa Orc Quebrada", Icon: "🔰", Rarity: "Incomum", Description: "Fragmento mágico de um orc mago.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_skeleton_bone", Name: "Osso do Esquelético", Icon: "🦴", Rarity: "Comum", Description: "Osso antigo usado em reforços.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_orc_bowstring", Name: "Corda de Arco Orc", Icon: "🏹", Rarity: "Incomum", Description: "Corda reaproveitável de arqueiro orc.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_berserker_buckle", Name: "Fivela do Berserker", Icon: "💢", Rarity: "Incomum", Description: "Metal amassado pela fúria.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_ninja_cloth", Name: "Tecido do Clã do Pé", Icon: "🥷", Rarity: "Incomum", Description: "Faixa negra de um ninja do esgoto.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_rat_tongue", Name: "Língua do Rato do Esgoto", Icon: "🐀", Rarity: "Incomum", Description: "Componente mutante de gosto duvidoso.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_destroyer_blade", Name: "Lasca da Lâmina do Destruidor", Icon: "🗡️", Rarity: "Raro", Description: "Fragmento envenenado de chefe.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_militant_shirt", Name: "Camisa do Militante 13", Icon: "👕", Rarity: "Incomum", Description: "Tecido vermelho carregado de convicção.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_patriot_flag", Name: "Retalho da Bandeira do Patriota", Icon: "🇧🇷", Rarity: "Incomum", Description: "Retalho que sobreviveu ao caminhão.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_riot_plate", Name: "Placa do Colete da Puliça", Icon: "🛡️", Rarity: "Incomum", Description: "Placa tática empenada.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_xandaum_pen", Name: "Ponta da Caneta de Xandaum", Icon: "🖊️", Rarity: "Raro", Description: "Assina receitas sem direito a recurso.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 2, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_dementor_cloth", Name: "Tecido do Desânimo", Icon: "🧥", Rarity: "Raro", Description: "Tecido que drena a alegria do ambiente.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 3, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_troll_hide", Name: "Couro de Troll", Icon: "🟩", Rarity: "Raro", Description: "Couro espesso com regeneração residual.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 3, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_dark_wand", Name: "Lasca da Varinha sem Nariz", Icon: "🪄", Rarity: "Épico", Description: "Fragmento sombrio de um arquimago.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 3, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_frozen_soul", Name: "Essência de Alma Congelada", Icon: "👻", Rarity: "Raro", Description: "Alma cristalizada pelo frio.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 4, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_zombie_frost", Name: "Medula Congelada", Icon: "🧟", Rarity: "Raro", Description: "Material necrosado e gelado.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 4, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_golem_core", Name: "Núcleo de Golem Glacial", Icon: "🧊", Rarity: "Épico", Description: "Coração mineral de um golem.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 4, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_chimera_horn", Name: "Chifre de Quimera", Icon: "🦄", Rarity: "Épico", Description: "Chifre gélido de criatura híbrida.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 4, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_sanctuary_crown", Name: "Fragmento da Coroa do Santuário", Icon: "🌟", Rarity: "Épico", Description: "Fragmento de autoridade congelada.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 4, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_dragon_scale", Name: "Escama Cinderina", Icon: "🐉", Rarity: "Épico", Description: "Escama resistente ao fogo abissal.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 5, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_demon_horn", Name: "Chifre de Demônio", Icon: "😈", Rarity: "Épico", Description: "Chifre denso do abismo.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 5, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_vampire_fang", Name: "Presa de Vampiro Ancestral", Icon: "🧛", Rarity: "Épico", Description: "Presa ainda impregnada de sangue.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 5, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_necromancer_rune", Name: "Runa do Necromante", Icon: "☠️", Rarity: "Épico", Description: "Runa que insiste em sussurrar.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 5, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_scorpion_stinger", Name: "Ferrão Infernal", Icon: "🦂", Rarity: "Épico", Description: "Ferrão carregado de veneno.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 5, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_flame_heart", Name: "Coração do Senhor das Chamas", Icon: "🔥", Rarity: "Lendário", Description: "Núcleo vivo de fogo.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 5, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
		{Key: "part_avenger_horn", Name: "Lasca do Chifre do Vingador", Icon: "🐲", Rarity: "Lendário", Description: "Componente supremo do chefe abissal.", MaxStack: 999999, Category: ResourceCategoryMonsterPart, CountsTowardStorage: true, Discardable: true, SourceKind: "monster_drop", Tier: 5, StorageWeight: 1, Tradeable: true, ContentVersion: 2},
	}
	for _, definition := range definitions {
		_ = RegisterResourceDefinition(definition)
	}
}

func init() {
	EnsureEconomyResourcesRegistered()
}

func EnsureEconomyResourcesRegistered() {
	economyResourcesOnce.Do(registerEconomyResources)
}
